services:
  api:
    image: traefik/whoami
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.gbnt.node.role == worker
          - ingress.host == api.gubernator.local
