site_name: Gubernator Orchestrator
site_description: A lightweight, hybrid container orchestrator built in Go.
site_author: Mario Ezquerro
repo_url: https://github.com/mario-ezquerro/gubernator

theme:
  name: material
  logo: gubernator-icon.png
  favicon: gubernator-icon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - toc.integrate

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - CLI Reference: cli.md
  - Architecture: architecture.md
  - API & SDK: api.md
  - Examples: examples.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
