

volumes:
  jupyter_workspace:

services:
  jupyter:
    image: quay.io/jupyter/minimal-notebook:latest
    container_name: jupyter_notebook
    restart: unless-stopped
    ports:
      - "127.0.0.1::8888"
    environment:
      - JUPYTER_TOKEN=gubernator-secret
      - JUPYTER_ENABLE_LAB=yes
    labels:
      - "ingress.host=jupyter.gbnt.local"
      - "gbnt.caddy.port=8888"
      - "gbnt.node.hostname=gbnt-worker2"
    volumes:
      - jupyter_workspace:/home/jovyan/work
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2G
        reservations:
          cpus: "0.5"
          memory: 512M

