services:
  whoami:
    image: traefik/whoami
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.25"
          memory: 128M
        reservations:
          cpus: "0.05"
          memory: 32M
      placement:
        constraints:
          - stack.name == test-app
          - node.labels.gbnt.node.role == worker
          # The magic label that tells Gubernator to configure Caddy
          - ingress.host == whoami.gubernator.local
