services:
  whoami:
    image: traefik/whoami
    deploy:
      replicas: 1
      placement:
        constraints:
          - stack.name == test-app
          - node.labels.gbnt.node.role == worker
          # The magic label that tells Gubernator to configure Caddy
          - ingress.host == whoami.gubernator.local
