package api

import (
	"fmt"
	"log"
	"net/http"
	"os"
	"strings"
	"time"

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	// This import is needed for swagger side-effects, it will be generated by swag init
	_ "github.com/mario-ezquerro/gubernator/docs"
	"github.com/mario-ezquerro/gubernator/internal/coredns"
	"github.com/mario-ezquerro/gubernator/internal/db"
	"github.com/mario-ezquerro/gubernator/internal/monitor"
	"github.com/mario-ezquerro/gubernator/internal/telemetry"
	"github.com/mario-ezquerro/gubernator/internal/web"
)

// Start initializes the Gin router and starts the REST API server on port 4000.
func Start() {
	// Initialize the Database
	db.Init("gubernator.db")

	// ── CoreDNS: Ensure gbnt-net network and CoreDNS container are running ──
	// This is the core DNS infrastructure for all Gubernator-managed containers.
	// gbnt-net: shared bridge network where all managed containers resolve *.gbnt
	// gbnt-coredns: CoreDNS container serving the .gbnt zone
	if err := coredns.EnsureNetwork(); err != nil {
		log.Printf("⚠️  CoreDNS: failed to create gbnt-net network: %v", err)
	} else {
		go func() {
			// Small delay to allow Docker daemon to fully register the network
			time.Sleep(2 * time.Second)
			if err := coredns.EnsureRunning(); err != nil {
				log.Printf("⚠️  CoreDNS: failed to start gbnt-coredns container: %v", err)
			}
		}()
	}

	// Start Background Healthchecks & Metrics Updater
	go startWatchtowers()

	// Start Web Dashboard on port 4001 (if env vars are set)
	go web.StartDashboard()

	// Start Telemetry & Swagger on port 4002
	go startTelemetryServer()

	// Start Local Executor: run pending tasks assigned to the local manager node
	go startLocalExecutor()

	// Auto-deploy SRE Monitoring Stack if GBNT_MONITOR=true
	monitorEnabled := strings.ToLower(os.Getenv("GBNT_MONITOR"))
	if monitorEnabled == "true" || monitorEnabled == "1" {
		go func() {
			// Wait for Docker and API to be fully ready
			time.Sleep(5 * time.Second)
			fmt.Println("\n🛡️  Auto-deploying SRE Monitoring Stack (GBNT_MONITOR=true)...")
			if err := monitor.EnsureNetwork(); err != nil {
				fmt.Printf("❌ SRE Monitor: failed to create network: %v\n", err)
				return
			}
			if err := monitor.WriteConfigs(nil); err != nil {
				fmt.Printf("❌ SRE Monitor: failed to write configs: %v\n", err)
				return
			}
			if err := monitor.DeployManagerStack(); err != nil {
				fmt.Printf("❌ SRE Monitor: deployment failed: %v\n", err)
				return
			}
			// Register monitoring containers in the database for dashboard visibility
			if err := monitor.RegisterInDB(db.GetDB()); err != nil {
				fmt.Printf("⚠️  SRE Monitor: failed to register in DB: %v\n", err)
			}
			fmt.Println("\n✅ SRE Monitoring Stack auto-deployed successfully!")
			fmt.Println("  📈 Grafana: http://localhost:3000  |  🔥 Prometheus: http://localhost:9090  |  📋 Loki: http://localhost:3100")
		}()
	}

	r := gin.Default()

	// API Authentication Middleware
	r.Use(func(c *gin.Context) {
		expectedToken := os.Getenv("GBNT_API_TOKEN")
		if expectedToken == "" {
			expectedToken = "admin" // default fallback
		}

		authHeader := c.GetHeader("Authorization")
		if authHeader != "Bearer "+expectedToken {
			c.AbortWithStatusJSON(401, gin.H{"error": "Unauthorized API access. Invalid or missing Bearer token."})
			return
		}
		c.Next()
	})

	// v1 group
	v1 := r.Group("/v1")
	{
		node := v1.Group("/node")
		{
			// Existing node logic
			node.GET("/ls", NodeListHandler)
			node.POST("/join", NodeJoinHandler)
			node.POST("/heartbeat", NodeHeartbeatHandler)
			node.GET("/tasks/:node_id", NodeTasksHandler)
			node.POST("/tasks/:task_id/status", UpdateTaskStatusHandler)

			// New CRUD node logic
			node.GET("/:id", NodeInspectHandler)
			node.POST("/:id/role", NodeRoleHandler)
			node.POST("/:id/availability", NodeAvailabilityHandler)
			node.POST("/:id/leave", NodeLeaveHandler)
		}

		cluster := v1.Group("/cluster")
		{
			cluster.GET("/token", ClusterTokenHandler)
		}

		stack := v1.Group("/stack")
		{
			stack.POST("/deploy", StackDeployHandler)
			stack.GET("/ls", StackListHandler)
			stack.GET("/:id/services", StackServicesHandler)
			stack.DELETE("/:id", StackRmHandler)
		}

		service := v1.Group("/service")
		{
			service.GET("/ls", ServiceListHandler)
			service.GET("/:id/tasks", ServiceTasksHandler)
			service.DELETE("/:id", ServiceRmHandler)
			service.POST("/:id/scale", ServiceScaleHandler)
		}

		task := v1.Group("/task")
		{
			task.GET("/ls", TaskListHandler)
			task.DELETE("/:id", TaskRmHandler)
		}
	}

	log.Println("Starting Gubernator Manager API on :4000")
	if err := r.Run(":4000"); err != nil {
		log.Fatalf("Failed to start API server: %v", err)
	}
}

// startTelemetryServer runs on port 4002 serving Swagger, Metrics and Healthchecks
func startTelemetryServer() {
	r := gin.Default()

	r.GET("/health", func(c *gin.Context) {
		c.JSON(200, gin.H{"status": "healthy"})
	})

	r.GET("/metrics", telemetry.MetricsHandler())
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	log.Println("Starting Telemetry, Health & Swagger API on :4002")
	if err := r.Run(":4002"); err != nil {
		log.Fatalf("Failed to start Telemetry server: %v", err)
	}
}

// NodeListResponse represents the response for the node ls endpoint
type NodeListResponse struct {
	Nodes []db.Node `json:"nodes"`
}

// @Summary List all nodes
// @Description Get a list of all nodes currently registered in the Gubernator cluster from SQLite
// @Tags nodes
// @Produce json
// @Success 200 {object} NodeListResponse
// @Router /v1/node/ls [get]
func NodeListHandler(c *gin.Context) {
	var nodes []db.Node
	if err := db.DB.Find(&nodes).Error; err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to fetch nodes"})
		return
	}

	c.JSON(http.StatusOK, NodeListResponse{
		Nodes: nodes,
	})
}

// startWatchtowers runs a background loop to update telemetry metrics
// and check for stale nodes (missed heartbeats).
func startWatchtowers() {
	for {
		time.Sleep(15 * time.Second)

		// 1. Update Metrics
		var nodeCount int64
		db.DB.Model(&db.Node{}).Count(&nodeCount)
		telemetry.TotalNodes.Set(float64(nodeCount))

		var taskCount int64
		db.DB.Model(&db.Task{}).Count(&taskCount)
		telemetry.TotalTasks.Set(float64(taskCount))

		// 2. Healthchecks: Mark nodes as 'down' if no heartbeat in 30 seconds
		threshold := time.Now().Add(-30 * time.Second)
		db.DB.Model(&db.Node{}).
			Where("role = ?", "worker").
			Where("updated_at < ?", threshold).
			Where("status = ?", "active").
			Updates(map[string]interface{}{"status": "down"})
	}
}
