version: "3.8"
name: slo-billing-service

services:
  billing-api:
    image: hashicorp/http-echo:latest
    command: ["-text=Billing Service OK", "-listen=:8082"]
    ports:
      - "8082:8082"
    labels:
      gbnt.slo.enable: "true"
      gbnt.slo.target: "99.0"
      gbnt.slo.window: "30d"
      gbnt.slo.sli.error_query: 'sum(rate(caddy_http_response_status_code_total{status=~"5.."}[5m]))'
      gbnt.slo.sli.total_query: 'sum(rate(caddy_http_response_status_code_total[5m]))'
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.gbnt.node.role == worker
          - ingress.host == billing.gbnt.local
