# Auto-generated by Terraform (Proxmox VE Provider)
[manager]
gbnt-manager ansible_host=${manager_ip} %{ if manager_storage_ip != "" }storage_ip=${manager_storage_ip}%{ endif } ansible_user=${ssh_user} ansible_ssh_private_key_file=${ssh_key} gbnt_node_role=manager

[workers]
%{ for index, ip in worker_ips ~}
gbnt-worker${index + 1} ansible_host=${ip} %{ if worker_storage_ips[index] != "" }storage_ip=${worker_storage_ips[index]}%{ endif } ansible_user=${ssh_user} ansible_ssh_private_key_file=${ssh_key} gbnt_node_role=worker gbnt_zone=proxmox-zone-${index + 1}
%{ endfor ~}

[cluster:children]
manager
workers

[cluster:vars]
ansible_python_interpreter=/usr/bin/python3
