services:
  hello-app:
    image: busybox:latest
    command: 'sh -c "mkdir -p /www && echo hola contenedor \$(hostname) > /www/index.html && httpd -f -p 80 -h /www"'
    deploy:
      replicas: 2
      placement:
        constraints:
          - stack.name == hello-lb
          - ingress.host == hello-102.gbnt.local

