# Auto-generated by Terraform (Hetzner Cloud Provider)
[manager]
gbnt-manager ansible_host=${manager_ip} ansible_user=${ssh_user} ansible_ssh_private_key_file=${ssh_key} gbnt_node_role=manager

[workers]
%{ for index, ip in worker_ips ~}
gbnt-worker${index + 1} ansible_host=${ip} ansible_user=${ssh_user} ansible_ssh_private_key_file=${ssh_key} gbnt_node_role=worker gbnt_zone=hetzner-zone-${index + 1}
%{ endfor ~}

[cluster:children]
manager
workers

[cluster:vars]
ansible_python_interpreter=/usr/bin/python3
