---
# ==============================================================================
# Gubernator Cluster Inventory Example (YAML Format)
# ==============================================================================
all:
  children:
    cluster:
      vars:
        ansible_python_interpreter: /usr/bin/python3
      children:
        manager:
          hosts:
            gbnt-manager:
              ansible_host: 192.168.1.10
              storage_ip: 10.10.100.10
              ansible_user: ubuntu
              ansible_ssh_private_key_file: ~/.ssh/id_rsa
              gbnt_node_role: manager
        workers:
          hosts:
            gbnt-worker1:
              ansible_host: 192.168.1.11
              storage_ip: 10.10.100.11
              ansible_user: ubuntu
              ansible_ssh_private_key_file: ~/.ssh/id_rsa
              gbnt_node_role: worker
              gbnt_zone: europe-west1
            gbnt-worker2:
              ansible_host: 192.168.1.12
              storage_ip: 10.10.100.12
              ansible_user: ubuntu
              ansible_ssh_private_key_file: ~/.ssh/id_rsa
              gbnt_node_role: worker
              gbnt_zone: europe-west2
            gbnt-worker3:
              ansible_host: 192.168.1.13
              storage_ip: 10.10.100.13
              ansible_user: rocky
              ansible_ssh_private_key_file: ~/.ssh/id_rsa
              gbnt_node_role: worker
              gbnt_zone: europe-west1
              gbnt_gpu: nvidia
