services:
  db:
    image: mysql:8.0
    container_name: db_wordpress
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: admin
    volumes:
      - db_data_{{stack.name}}:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    container_name: app_wordpress
    restart: always
    ports:
      - "127.0.0.1::80"
    environment:
      WORDPRESS_DB_HOST: db.{{stack.name}}.gbnt:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: admin
    deploy:
      replicas: 1
      placement:
        constraints:
          - stack.name == wp
          - ingress.host == hello-101.gbnt.test
    depends_on:
      - db
    volumes:
      - wp_data_{{stack.name}}:/var/www/html

volumes:
  db_data_{{stack.name}}:
  wp_data_{{stack.name}}:
